/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegularizacaoDeImoveisRouteImport } from './routes/regularizacao-de-imoveis'
import { Route as QuemERouteImport } from './routes/quem-e'
import { Route as PoliticaDePrivacidadeRouteImport } from './routes/politica-de-privacidade'
import { Route as LeilaoDeImoveisRouteImport } from './routes/leilao-de-imoveis'
import { Route as LeilaoRouteImport } from './routes/leilao'
import { Route as IndexRouteImport } from './routes/index'

const RegularizacaoDeImoveisRoute = RegularizacaoDeImoveisRouteImport.update({
  id: '/regularizacao-de-imoveis',
  path: '/regularizacao-de-imoveis',
  getParentRoute: () => rootRouteImport,
} as any)
const QuemERoute = QuemERouteImport.update({
  id: '/quem-e',
  path: '/quem-e',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliticaDePrivacidadeRoute = PoliticaDePrivacidadeRouteImport.update({
  id: '/politica-de-privacidade',
  path: '/politica-de-privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const LeilaoDeImoveisRoute = LeilaoDeImoveisRouteImport.update({
  id: '/leilao-de-imoveis',
  path: '/leilao-de-imoveis',
  getParentRoute: () => rootRouteImport,
} as any)
const LeilaoRoute = LeilaoRouteImport.update({
  id: '/leilao',
  path: '/leilao',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/leilao': typeof LeilaoRoute
  '/leilao-de-imoveis': typeof LeilaoDeImoveisRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/quem-e': typeof QuemERoute
  '/regularizacao-de-imoveis': typeof RegularizacaoDeImoveisRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/leilao': typeof LeilaoRoute
  '/leilao-de-imoveis': typeof LeilaoDeImoveisRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/quem-e': typeof QuemERoute
  '/regularizacao-de-imoveis': typeof RegularizacaoDeImoveisRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/leilao': typeof LeilaoRoute
  '/leilao-de-imoveis': typeof LeilaoDeImoveisRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/quem-e': typeof QuemERoute
  '/regularizacao-de-imoveis': typeof RegularizacaoDeImoveisRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/leilao'
    | '/leilao-de-imoveis'
    | '/politica-de-privacidade'
    | '/quem-e'
    | '/regularizacao-de-imoveis'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/leilao'
    | '/leilao-de-imoveis'
    | '/politica-de-privacidade'
    | '/quem-e'
    | '/regularizacao-de-imoveis'
  id:
    | '__root__'
    | '/'
    | '/leilao'
    | '/leilao-de-imoveis'
    | '/politica-de-privacidade'
    | '/quem-e'
    | '/regularizacao-de-imoveis'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LeilaoRoute: typeof LeilaoRoute
  LeilaoDeImoveisRoute: typeof LeilaoDeImoveisRoute
  PoliticaDePrivacidadeRoute: typeof PoliticaDePrivacidadeRoute
  QuemERoute: typeof QuemERoute
  RegularizacaoDeImoveisRoute: typeof RegularizacaoDeImoveisRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/regularizacao-de-imoveis': {
      id: '/regularizacao-de-imoveis'
      path: '/regularizacao-de-imoveis'
      fullPath: '/regularizacao-de-imoveis'
      preLoaderRoute: typeof RegularizacaoDeImoveisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quem-e': {
      id: '/quem-e'
      path: '/quem-e'
      fullPath: '/quem-e'
      preLoaderRoute: typeof QuemERouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politica-de-privacidade': {
      id: '/politica-de-privacidade'
      path: '/politica-de-privacidade'
      fullPath: '/politica-de-privacidade'
      preLoaderRoute: typeof PoliticaDePrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leilao-de-imoveis': {
      id: '/leilao-de-imoveis'
      path: '/leilao-de-imoveis'
      fullPath: '/leilao-de-imoveis'
      preLoaderRoute: typeof LeilaoDeImoveisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leilao': {
      id: '/leilao'
      path: '/leilao'
      fullPath: '/leilao'
      preLoaderRoute: typeof LeilaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LeilaoRoute: LeilaoRoute,
  LeilaoDeImoveisRoute: LeilaoDeImoveisRoute,
  PoliticaDePrivacidadeRoute: PoliticaDePrivacidadeRoute,
  QuemERoute: QuemERoute,
  RegularizacaoDeImoveisRoute: RegularizacaoDeImoveisRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
